[package]
name = "rust-journal"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
home = "0.5"
serde_json = "1.0"   # Add serde_json.
structopt = "0.3.26"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1.0"
